version: '3.7'

services:

  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
      - "443:443"
    volumes:
      - ./backend:/var/www/html
      - ./.cloud/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - public
    depends_on:
      - php
      - mysql

  mysql:
    image: mysql:5.7.29
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: starter
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - mysql-data:/var/lib/mysql/
      - ./.cloud/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - public

  php:
    build: .cloud/docker
    restart: unless-stopped
    tty: true
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/var/www/html
      - ./.cloud/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - public

  redis:
    image: redis
    restart: unless-stopped
    tty: true
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - public

volumes:
  mysql-data:
  redis-data:

networks:
  public: